language: node_js
node_js:
  - "8"

services:
  - docker

install:
  - docker pull darksheer/sles12:latest
  - docker run -d darksheer/sles12:latest -v /home/travis/build/frumania/aws-sap-scripts:/aws-sap-scripts
#  - docker run -i -t toolsmiths/sles-dev /bin/bash
 
#before_script:
#  - npm install

script:
  - pwd
  - docker ps