language: python
python:
  - "3.6"

install:
  - pip3 install awscli
 
#before_script:
#  - npm install

script:
#  - aws s3 ls s3://sap-sources
  - aws --version
  - chmod 700 test/test_sles.sh
  - chmod 700 test/test_win.sh
  - bash test/test_sles.sh
  - bash test/test_win.sh