language: node_js
node_js:
  - "8"

services:
  - docker

install:
  - docker pull darksheer/sles12:latest
 
#before_script:
#  - npm install

script:
  - pwd
  - chmod 777 /home/travis/build/frumania/aws-sap-scripts/test/test.sh
  - docker run --name sles --mount type=bind,src=/home/travis/build/frumania/aws-sap-scripts,dst=/aws-sap-scripts -dit darksheer/sles12 /aws-sap-scripts/test/test.sh  
  - docker logs -f sles