language: node_js
node_js:
  - "8"

services:
  - docker

install:
  - docker pull darksheer/sles12:latest
 
#before_script:
#  - npm install

script:
  - pwd
  - docker run -d darksheer/sles12:latest --name sles --mount type=bind,src=/home/travis/build/frumania/aws-sap-scripts,dst=/aws-sap-scripts
  - docker ps