language: python
python:
  - "3.6"

install:
  - pip3 install awscli
 
#before_script:
#  - npm install

script:
  - printf '$key\n$secret\neu-central-1\n\n\n' | aws configure
  - aws s3 ls s3://sap-sources